### PR TITLE
Bugfix - Version Prefix in Plugins

### LINKED ISSUE #31: Version prefix not applying to current version in plugins
Using the example plugin without modification, the "current version" argument doesn't contain VERSION_PREFIX config setting.

See output:

```
$ git semver minor

User plugin "example.sh":

  New version: v0.2.0
  Current version: 0.1.0
  ...
v0.2.0
```

Notice how "current version" is "0.1.0" while new version is "v0.2.0" (with v)

This seems to be because the `version-do` method is being called without the VERSON_PREFIX for `$version` in `version-major`, `version-minor`, and `version-patch` :

https://github.com/markchalloner/git-semver/blob/d838cb34780a29d104ed20ef18465c44918b0f64/git-semver.sh#L165

I can make a PR.

### PR DESCRIPTION
**Pull request by srt4rulez**
Fixes #31

### CODE REVIEW

**Comment by srt4rulez** [comment]
@markchalloner Let me know what you think of this solution. 👍

**Comment by srt4rulez** [comment]
Ah, it seems there were some major changes from #27. I'll have to re-think the solution to this.

**Comment by oliviabarrick** [comment]
I ran into a possibly related bug. Try my branch and see if it fixes the issue you're seeing? https://github.com/markchalloner/git-semver/pull/33

**Comment by srt4rulez** [comment]
Yup! That seems to work fine for me. Thanks! Closing this PR.

**Pull request closed without merging**
